name: Auto Version & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bump version and commit
        run: |
          NEW_VERSION="1.0.$(date +%s)"
          echo "$NEW_VERSION" > version.txt

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release v${{ steps.setver.outputs.version }}"
          tag_name: "v${{ steps.setver.outputs.version }}"
          body_path: RELEASE_NOTES.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
