name: swift ci

on:
 push:
  branches: [ "main", "qa", "dev" ]
 pull_request:
  branches: [ "main", "qa", "dev", "feature/*", "realese/*" ]

jobs:
 lint:
  runs-on: macos-latest

  steps:
   - name: check the code
     uses: actions/checkout@v4

   - name: setup swiftlint
     uses: norio-nomura/action-swiftlint@3.2.1
     with:
      args: --strict

 unit-test:
  needs: [lint]
  runs-on: macos-latest

  steps:
   - name: checkout the code 
     uses: actions/checkout@v4

   - name: Run swift test
     run: swift test

 build:
  needs: [lint, unit-test]
  runs-on: macos-latest

  steps:
   - name: swift build
     run: |
      swift--version
      swift build--clean
      swift build
      
  
